#!/bin/bash
# Begin LSF directives
#BSUB -P csc380
#BSUB -J LSMS-FePt216
#BSUB -o FePt.stdout
#BSUB -W 2:00
#BSUB -nnodes 4
# End LSF directives and begin shell commands

export LSMS_ROOT=$HOME/mstsuite/lsms
# cd $MEMBERWORK/stf006/Fe
cd $LS_SUBCWD

date
jsrun -n 24 -a 1 -g 1 -c 7 -b packed:7 $LSMS_ROOT/bin/lsms i_lsms

