#!/bin/bash

j=0

for ((i=1; i<=$#; i++)); do
  if [ ${!i} = "--input" ]
     then
        j=$((i+1))
        echo "Input file: ${!j}"
  elif [ ${!i} = "-i" ]
     then
        j=$((i+1))
        echo "Input file: ${!j}"
  fi
done

for n in `ls POSCAR-* | sed -e s/POSCAR-//g` ; do
    mkdir disp-$n
    cp POSCAR-$n disp-$n
    cp *_mt_v disp-$n
    if (( j > 0 )); then
       cp ${!j} disp-$n
    fi
done
